### ISSUE TITLE
ValueError("call must be a callable")

### ISSUE THREAD

**Issue by ceskvfx** [RicardoMusch/rtm-tk-nuke-lut-app#1]
Hi Ricardo, thanks for the app but I have these error with v0.1 any idea?
Thanks

2020-05-15 13:33:35,127 [7584 INFO sgtk.env.project.tk-nuke.tk-multi-workfiles2] Changing context from Project XXX to TST, Shot 0010
2020-05-15 13:33:35,394 [7584 ERROR sgtk.env.project.tk-nuke.rtm-tk-nuke-lut-app] Adding C:\Users\ZZZZZ\Desktop\PRX_SG_PIPE\config\hooks\tk-nuke\tk-nuke-lut-app to nuke plugin path
2020-05-15 13:33:35,788 [7584 ERROR sgtk.env.project.tk-nuke] App C:\Users\ZZZZZ\Desktop\PRX_SG_PIPE\install\git\rtm-tk-nuke-lut-app.git\v0.1 failed to initialize. It will not be loaded.
Traceback (most recent call last):
  File "C:\Users\ZZZZZ\Desktop\PRX_SG_PIPE\install\core\python\tank\platform\engine.py", line 2792, in __load_apps
    app.init_app()
  File "C:\Users\ZZZZZ\Desktop\PRX_SG_PIPE\install\git\rtm-tk-nuke-lut-app.git\v0.1\app.py", line 84, in init_app
    nuke.addOnScriptSave(loadLut())
  File "C:/Program Files/Nuke11.3v2/plugins\nuke\callbacks.py", line 87, in addOnScriptSave
    _addCallback(onScriptSaves, call, args, kwargs, nodeClass)
  File "C:/Program Files/Nuke11.3v2/plugins\nuke\callbacks.py", line 14, in _addCallback
    raise ValueError("call must be a callable")
ValueError: call must be a callable

**Comment by RicardoMusch** [comment]
Hey!

sorry for the delay.
I forgot to mark this repo as archived as I'm no longer maintaining it and the code is definitely very buggy.
I may revisit it at some point but not at the moment.

With regards to your issue,

I think in the code it's trying to add the callback too early during launch.

**Comment by ceskvfx** [comment]
Thanks Ricardo!
